PhoneBookGo.UI/ViewModels/IndexViewModel.cs
using PhoneBookGo.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneBookGo.UI.ViewModels
{
    public class IndexViewModel
    {
        public List<Person> People { get; set; }
        public string Pattern { get; set; }
    }
}

PhoneBookGo.UI/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhoneBookGo.Data.Models;
using PhoneBookGo.IO.Interfaces;

namespace PhoneBookGo.UI.Controllers
{
    public class ManagementController : Controller
    {
        private readonly IDatabaseReader _dbReader;
        private readonly IDatabaseWriter _dbWriter;

        public ManagementController(IDatabaseReader dbReader, IDatabaseWriter dbWriter)
        {
            _dbReader = dbReader;
            _dbWriter = dbWriter;
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var result = _dbReader.SelectPerson(id);

            if (!result.IsFine)
            {
                return RedirectToAction("Error", $"System was unable to edit person.");
            }

            return View(result.Output);
        }

        [HttpPost]
        public IActionResult Edit(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            var result = _dbWriter.UpdatePerson(person);

            if (result.IsFine)
            {
                return RedirectToAction("Index", "PhoneBook");
            }

            return RedirectToAction("Error", $"System was unable to update person {person.ToString()}.");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new Person());
        }

        [HttpPost]
        public IActionResult Add(Person person)
        {
            if (!ModelState.IsValid)
            {
                return View(person);
            }

            var result = _dbWriter.InsertPerson(person);

            if (result.IsFine)
            {
                return RedirectToAction("Index", "PhoneBook");
            }

            return RedirectToAction("Error", $"System was unable to add new person {person.ToString()}.");
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {

            var result = _dbWriter.DeletePerson(id);

            if (result.IsFine)
            {
                return RedirectToAction("Index", "PhoneBook");
            }

            return RedirectToAction("Error", $"System was unable to delete person.");
        }

        [HttpGet]
        public IActionResult Error(string message)
        {
            return View(message);
        }
    }
}

PhoneBookGo.UI/Controllers/PhoneBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhoneBookGo.Data.Models;
using PhoneBookGo.IO.Interfaces;
using PhoneBookGo.UI.ViewModels;

namespace PhoneBookGo.UI.Controllers
{
    public class PhoneBookController : Controller
    {
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        private readonly IDatabaseReader _dbReader;

        public PhoneBookController(IDatabaseReader dbReader)
        {
            _dbReader = dbReader;
        }

        [HttpGet]
        public IActionResult Index(int page = 1)
        {
            var people = _dbReader.SelectPeople();
            if (!people.IsFine)
            {
                return RedirectToAction("Error");
            }

            var pages = (int)Math.Ceiling(people.Output.Count() / 3d);

            if (page <= 0) { page = 1; }

            else if(page > pages)
            {
                page = pages;
            }

            var result = people.Output
                .Skip((page - 1) * 3)
                .Take(3)
                .ToList();

            var viewModel = new IndexViewModel();
            viewModel.Pattern = "";
            viewModel.People = result;
            ViewBag.Title = "Main page";
            ViewBag.Pages = pages;
            ViewBag.Page = page;
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Error(string error)
        {
            return View(error);
        }
    }
}

PhoneBookGo.UI/Views/Management/Add.cshtml
@model Person
@{
    ViewData["Title"] = "Add";
}

<h1 class="bg-success text-center">Add</h1>
<form asp-action="Add" asp-antiforgery="true">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span asp-validation-for="Email"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PhoneBookGo.UI/Views/Management/Edit.cshtml
@model  Person
@{
    ViewData["Title"] = "Edit";
}

<h1 class="bg-warning text-center">Edit</h1>
<form asp-action="Edit" asp-antiforgery="true">
    <div class="form-group">
        <input class="form-control" asp-for="ID" hidden="hidden"/>
    </div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
        <span asp-validation-for="LastName"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span asp-validation-for="Email"></span>
    </div>

    <div class="form-group mb-2">
        <label asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PhoneBookGo.UI/Views/PhoneBook/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Index";
}

<h1 class="bg-info text-center">Index - page @ViewBag.Page</h1>

@if(!Model.People.Any())
{
    <h2 class="text-center">Whoah! It looks like you have no contacts... Lets <a asp-action="Add" asp-controller="Management">add</a> new!</h2>
}

<table class="table table-dark table-striped table-hover">
    <thead class="thead-light">
        <tr>
            <td>Name</td>
            <td>Last name</td>
            <td>Phone</td>
            <td>Email</td>
            <td>Created</td>
            <td>Last modified</td>
            <td colspan="2">Options</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model.People)
        {
            <tr>
                <td>@person.Name</td>
                <td>@person.LastName</td>
                <td>@person.Phone</td>
                <td>@person.Email</td>
                <td>@person.Created</td>
                <td>@person.Modified</td>
                <td><a asp-action="Edit" asp-controller="Management" asp-route-id="@person.ID">Edit</a></td>
                <td><a asp-action="Remove" asp-controller="Management" asp-route-id="@person.ID">Remove</a></td>
            </tr>
        }
        <tr>
            <td colspan="8"><a asp-action="Add" asp-controller="Management">Add</a></td>
        </tr>
    </tbody>
</table>

@for(var i = 1; i <= ViewBag.Pages; i++)
{
    <a asp-action="Index" asp-controller="PhoneBook" asp-route-page="@i">Page @i</a> 
}

PhoneBookGo.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
          rel="stylesheet" 
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" 
          crossorigin="anonymous">
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>